# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.21.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.21.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hejixuan/Desktop/杂七杂八/科协/THUAI/thuai2021-egg-aisdk/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hejixuan/Desktop/杂七杂八/科协/THUAI/thuai2021-egg-aisdk/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.21.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hejixuan/Desktop/杂七杂八/科协/THUAI/thuai2021-egg-aisdk/cpp/CMakeFiles /Users/hejixuan/Desktop/杂七杂八/科协/THUAI/thuai2021-egg-aisdk/cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hejixuan/Desktop/杂七杂八/科协/THUAI/thuai2021-egg-aisdk/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

contestant_code.o: contestant_code.cpp.o
.PHONY : contestant_code.o

# target to build an object file
contestant_code.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/contestant_code.cpp.o
.PHONY : contestant_code.cpp.o

contestant_code.i: contestant_code.cpp.i
.PHONY : contestant_code.i

# target to preprocess a source file
contestant_code.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/contestant_code.cpp.i
.PHONY : contestant_code.cpp.i

contestant_code.s: contestant_code.cpp.s
.PHONY : contestant_code.s

# target to generate assembly for a file
contestant_code.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/contestant_code.cpp.s
.PHONY : contestant_code.cpp.s

egg_sdk.o: egg_sdk.cpp.o
.PHONY : egg_sdk.o

# target to build an object file
egg_sdk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/egg_sdk.cpp.o
.PHONY : egg_sdk.cpp.o

egg_sdk.i: egg_sdk.cpp.i
.PHONY : egg_sdk.i

# target to preprocess a source file
egg_sdk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/egg_sdk.cpp.i
.PHONY : egg_sdk.cpp.i

egg_sdk.s: egg_sdk.cpp.s
.PHONY : egg_sdk.s

# target to generate assembly for a file
egg_sdk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/egg_sdk.cpp.s
.PHONY : egg_sdk.cpp.s

schema.o: schema.cpp.o
.PHONY : schema.o

# target to build an object file
schema.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/schema.cpp.o
.PHONY : schema.cpp.o

schema.i: schema.cpp.i
.PHONY : schema.i

# target to preprocess a source file
schema.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/schema.cpp.i
.PHONY : schema.cpp.i

schema.s: schema.cpp.s
.PHONY : schema.s

# target to generate assembly for a file
schema.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/schema.cpp.s
.PHONY : schema.cpp.s

stream_helper.o: stream_helper.cpp.o
.PHONY : stream_helper.o

# target to build an object file
stream_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stream_helper.cpp.o
.PHONY : stream_helper.cpp.o

stream_helper.i: stream_helper.cpp.i
.PHONY : stream_helper.i

# target to preprocess a source file
stream_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stream_helper.cpp.i
.PHONY : stream_helper.cpp.i

stream_helper.s: stream_helper.cpp.s
.PHONY : stream_helper.s

# target to generate assembly for a file
stream_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stream_helper.cpp.s
.PHONY : stream_helper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... contestant_code.o"
	@echo "... contestant_code.i"
	@echo "... contestant_code.s"
	@echo "... egg_sdk.o"
	@echo "... egg_sdk.i"
	@echo "... egg_sdk.s"
	@echo "... schema.o"
	@echo "... schema.i"
	@echo "... schema.s"
	@echo "... stream_helper.o"
	@echo "... stream_helper.i"
	@echo "... stream_helper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

